#spring.application.name=test0
#spring.datasource.url=jdbc:postgresql://localhost:5432/test_zero
#spring.datasource.username=postgres
#spring.datasource.password=devashura
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.application.name=test0
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver